package fracdex

import (
	"math/rand"
	"sort"
	"strings"
	"testing"
)

// TestKeyBetweenVectors pins the exact output of the algorithm against the reference
// implementation. These are regression guards: if a refactor changes any of these, keys
// generated by an older build would interleave incorrectly with keys from a newer one.
func TestKeyBetweenVectors(t *testing.T) {
	cases := []struct{ a, b, want string }{
		{"", "", "a0"},
		{"", "a0", "Zz"},
		{"", "Zz", "Zy"},
		{"a0", "", "a1"},
		{"a1", "", "a2"},
		{"a0", "a1", "a0V"},
		{"a1", "a2", "a1V"},
		{"a0V", "a1", "a0l"},
		{"Zz", "a0", "ZzV"},
		{"Zz", "a1", "a0"},
		{"", "Y00", "Xzzz"},
		{"bzz", "", "c000"},
		{"a0", "a0V", "a0G"},
		{"a0", "a0G", "a08"},
		{"b125", "b129", "b127"},
		{"a0", "a1V", "a1"},
		{"Zz", "a01", "a0"},
		{"", "a0V", "a0"},
		{"", "b999", "b99"},
		{"", "A000000000000000000000000001", "A000000000000000000000000000V"},
		{"zzzzzzzzzzzzzzzzzzzzzzzzzzy", "", "zzzzzzzzzzzzzzzzzzzzzzzzzzz"},
		{"zzzzzzzzzzzzzzzzzzzzzzzzzzz", "", "zzzzzzzzzzzzzzzzzzzzzzzzzzzV"},
	}
	for _, tc := range cases {
		got, err := KeyBetween(tc.a, tc.b)
		if err != nil {
			t.Errorf("KeyBetween(%q, %q) returned error: %v", tc.a, tc.b, err)
			continue
		}
		if got != tc.want {
			t.Errorf("KeyBetween(%q, %q) = %q, want %q", tc.a, tc.b, got, tc.want)
		}
	}
}

func TestKeyBetweenRejectsBadInput(t *testing.T) {
	cases := []struct{ a, b, why string }{
		{"a00", "", "trailing zero in fraction"},
		{"a00", "a1", "trailing zero in fraction"},
		{"0", "1", "invalid integer head"},
		{"a1", "a0", "bounds out of order"},
		{"a1", "a1", "equal bounds"},
		{"", "A00000000000000000000000000", "reserved smallest integer"},
		{"a", "", "integer part shorter than declared length"},
	}
	for _, tc := range cases {
		if got, err := KeyBetween(tc.a, tc.b); err == nil {
			t.Errorf("KeyBetween(%q, %q) = %q, want error (%s)", tc.a, tc.b, got, tc.why)
		}
	}
}

// TestKeyBetweenIsStrictlyBetween is the property that actually matters. The vectors above
// prove we match the reference; this proves the invariant holds for arbitrary inputs.
func TestKeyBetweenIsStrictlyBetween(t *testing.T) {
	rng := rand.New(rand.NewSource(1))
	keys := []string{First()}

	for i := 0; i < 4000; i++ {
		idx := rng.Intn(len(keys) + 1)
		var lo, hi string
		if idx > 0 {
			lo = keys[idx-1]
		}
		if idx < len(keys) {
			hi = keys[idx]
		}

		k, err := KeyBetween(lo, hi)
		if err != nil {
			t.Fatalf("iteration %d: KeyBetween(%q, %q): %v", i, lo, hi, err)
		}
		if lo != "" && !(lo < k) {
			t.Fatalf("iteration %d: %q is not > lower bound %q", i, k, lo)
		}
		if hi != "" && !(k < hi) {
			t.Fatalf("iteration %d: %q is not < upper bound %q", i, k, hi)
		}

		keys = append(keys, "")
		copy(keys[idx+1:], keys[idx:])
		keys[idx] = k
	}

	// The whole list must still be in ascending order, with no duplicates.
	for i := 1; i < len(keys); i++ {
		if keys[i-1] >= keys[i] {
			t.Fatalf("ordering broken at %d: %q >= %q", i, keys[i-1], keys[i])
		}
	}
	if !sort.StringsAreSorted(keys) {
		t.Fatal("generated keys are not lexicographically sorted")
	}
}

// TestKeyLengthStaysBounded documents the accepted trade-off from the package doc: keys
// grow under repeated insertion at the same slot. This asserts the growth is linear-ish
// rather than explosive, and that we stay far inside the 128-char schema CHECK.
func TestKeyLengthStaysBounded(t *testing.T) {
	// Worst case: always insert immediately after the same key.
	lo, hi := First(), ""
	var err error
	hi, err = KeyBetween(lo, "")
	if err != nil {
		t.Fatal(err)
	}
	k := hi
	for i := 0; i < 100; i++ {
		k, err = KeyBetween(lo, k)
		if err != nil {
			t.Fatalf("iteration %d: %v", i, err)
		}
	}
	if len(k) > 128 {
		t.Fatalf("key grew to %d chars after 100 same-slot inserts: %q", len(k), k)
	}
	t.Logf("100 same-slot inserts produced a %d-char key", len(k))
}

// TestAppendKeysStayShort is the case that motivates the integer-part encoding: appending
// to the end is by far the most common operation, and it must not grow keys at all.
func TestAppendKeysStayShort(t *testing.T) {
	k := First()
	var err error
	for i := 0; i < 5000; i++ {
		if k, err = KeyBetween(k, ""); err != nil {
			t.Fatalf("append %d: %v", i, err)
		}
	}
	if len(k) > 6 {
		t.Errorf("after 5000 appends key is %d chars (%q); the integer encoding should keep this tiny", len(k), k)
	}
}

func TestNKeysBetween(t *testing.T) {
	cases := []struct {
		name string
		a, b string
		n    int
	}{
		{"unbounded both", "", "", 10},
		{"append", "a0", "", 25},
		{"prepend", "", "a0", 25},
		{"between", "a0", "a1", 50},
		{"zero", "a0", "a1", 0},
		{"one", "a0", "a1", 1},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			keys, err := NKeysBetween(tc.a, tc.b, tc.n)
			if err != nil {
				t.Fatalf("NKeysBetween(%q, %q, %d): %v", tc.a, tc.b, tc.n, err)
			}
			if len(keys) != tc.n {
				t.Fatalf("got %d keys, want %d", len(keys), tc.n)
			}
			if !sort.StringsAreSorted(keys) {
				t.Fatalf("keys not ascending: %v", keys)
			}
			for i, k := range keys {
				if tc.a != "" && k <= tc.a {
					t.Fatalf("key %d (%q) not > lower bound %q", i, k, tc.a)
				}
				if tc.b != "" && k >= tc.b {
					t.Fatalf("key %d (%q) not < upper bound %q", i, k, tc.b)
				}
				if i > 0 && keys[i-1] == k {
					t.Fatalf("duplicate key at %d: %q", i, k)
				}
			}
		})
	}
}

// TestNKeysBetweenBisects proves the bulk path is not just a chained loop: bisection keeps
// key length logarithmic in n, which is what makes seeding a long trip cheap.
func TestNKeysBetweenBisects(t *testing.T) {
	keys, err := NKeysBetween("a0", "a1", 1000)
	if err != nil {
		t.Fatal(err)
	}
	longest := 0
	for _, k := range keys {
		if len(k) > longest {
			longest = len(k)
		}
	}
	if longest > 12 {
		t.Errorf("longest key is %d chars; bisection should keep this logarithmic in n", longest)
	}
	t.Logf("1000 bisected keys, longest is %d chars", longest)
}

// TestConcurrentSameSlotInsertsAreDeterministic is the Stage 2 relevant property: two
// clients inserting into the same gap without seeing each other may produce identical
// position keys. That is fine and expected — convergence comes from the (position, id)
// tiebreak, which every replica computes identically. This test documents that contract
// so nobody "fixes" the duplicate by adding randomness later.
func TestConcurrentSameSlotInsertsAreDeterministic(t *testing.T) {
	clientA, err := KeyBetween("a0", "a1")
	if err != nil {
		t.Fatal(err)
	}
	clientB, err := KeyBetween("a0", "a1")
	if err != nil {
		t.Fatal(err)
	}
	if clientA != clientB {
		t.Fatalf("expected identical keys from identical bounds, got %q and %q", clientA, clientB)
	}

	// Both rows exist; ordering is resolved by id. Simulate the composite sort.
	type row struct{ position, id string }
	rows := []row{{clientB, "ffff"}, {clientA, "0000"}}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].position != rows[j].position {
			return rows[i].position < rows[j].position
		}
		return rows[i].id < rows[j].id
	})
	if rows[0].id != "0000" {
		t.Fatalf("tiebreak did not order by id: %+v", rows)
	}
}

func TestFirstIsValid(t *testing.T) {
	if err := validateOrderKey(First()); err != nil {
		t.Fatalf("First() produced an invalid key: %v", err)
	}
}

func TestDigitsAreAscending(t *testing.T) {
	// The entire scheme depends on ASCII byte order matching digit value.
	for i := 1; i < len(Digits); i++ {
		if Digits[i-1] >= Digits[i] {
			t.Fatalf("digit alphabet is not ascending at %d: %q >= %q", i, Digits[i-1], Digits[i])
		}
		if digitIndex(Digits[i]) != i {
			t.Fatalf("digitIndex(%q) = %d, want %d", Digits[i], digitIndex(Digits[i]), i)
		}
	}
	if len(Digits) != 62 {
		t.Fatalf("expected 62 digits, got %d", len(Digits))
	}
}

func TestIntegerRoundTrip(t *testing.T) {
	x := "a0"
	for i := 0; i < 200; i++ {
		next, err := incrementInteger(x)
		if err != nil {
			t.Fatalf("increment %d from %q: %v", i, x, err)
		}
		if next <= x {
			t.Fatalf("increment did not increase: %q -> %q", x, next)
		}
		back, err := decrementInteger(next)
		if err != nil {
			t.Fatalf("decrement from %q: %v", next, err)
		}
		if back != x {
			t.Fatalf("round trip failed: %q -> %q -> %q", x, next, back)
		}
		x = next
	}
}

func TestSmallestIntegerIsRejected(t *testing.T) {
	if !strings.HasPrefix(smallestInteger, "A") || len(smallestInteger) != 27 {
		t.Fatalf("smallestInteger malformed: %q (len %d)", smallestInteger, len(smallestInteger))
	}
	if err := validateOrderKey(smallestInteger); err == nil {
		t.Fatal("smallestInteger should be rejected as a key")
	}
}

func BenchmarkKeyBetween(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_, _ = KeyBetween("a0", "a1")
	}
}
