// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachmentExists = `-- name: AttachmentExists :one
SELECT EXISTS (SELECT 1 FROM attachments WHERE id = $1)
`

func (q *Queries) AttachmentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, attachmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const confirmAttachment = `-- name: ConfirmAttachment :one
UPDATE attachments
SET status          = 'ready',
    size_bytes      = $1,
    checksum_sha256 = $2,
    updated_at      = $3
WHERE id = $4 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at
`

type ConfirmAttachmentParams struct {
	SizeBytes      *int64
	ChecksumSha256 []byte
	UpdatedAt      time.Time
	ID             uuid.UUID
}

// The second phase of the upload. The `status = 'pending'` predicate is what makes this
// idempotent-safe and race-safe at once: a second confirmation, or a confirmation of something
// already failed or deleted, affects no rows rather than resurrecting it.
//
// Size and checksum are written from the server-side Stat, never from the client. A presigned
// PUT cannot enforce a size limit (D48), so these are the only trustworthy values in the row
// and they must arrive from the storage layer.
func (q *Queries) ConfirmAttachment(ctx context.Context, arg ConfirmAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, confirmAttachment,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.BudgetEntryID,
		&i.SlotID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.ExternalUrl,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalName,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO attachments (
  id, trip_id, slot_option_id, budget_entry_id, slot_id,
  kind, status, storage_key, external_url, content_type, original_name, uploaded_by
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at
`

type CreateAttachmentParams struct {
	ID            uuid.UUID
	TripID        uuid.UUID
	SlotOptionID  *uuid.UUID
	BudgetEntryID *uuid.UUID
	SlotID        *uuid.UUID
	Kind          string
	Status        string
	StorageKey    string
	ExternalUrl   string
	ContentType   string
	OriginalName  string
	UploadedBy    *uuid.UUID
}

// Queries for attachments — photos, ticket screenshots and links.
//
// Note what is absent: there is no UpdateAttachment. Attachments are immutable once ready
// (D46) — you replace one, you do not edit it — and the only state change in their life is the
// two-phase upload's pending -> ready confirmation, which is its own narrowly-scoped statement
// below. Adding a general update here would quietly give the entity a merge grain the sync
// vocabulary deliberately does not have.
// The exclusive arc is enforced by the schema's attachments_one_owner CHECK, not here: passing
// two owners produces a constraint violation that maps to a field-level error, rather than
// silently preferring one.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.TripID,
		arg.SlotOptionID,
		arg.BudgetEntryID,
		arg.SlotID,
		arg.Kind,
		arg.Status,
		arg.StorageKey,
		arg.ExternalUrl,
		arg.ContentType,
		arg.OriginalName,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.BudgetEntryID,
		&i.SlotID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.ExternalUrl,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalName,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.BudgetEntryID,
		&i.SlotID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.ExternalUrl,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OriginalName,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachmentsForBudgetEntry = `-- name: ListAttachmentsForBudgetEntry :many
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments
WHERE budget_entry_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsForBudgetEntry(ctx context.Context, budgetEntryID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForBudgetEntry, budgetEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.BudgetEntryID,
			&i.SlotID,
			&i.Kind,
			&i.Status,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OriginalName,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForOption = `-- name: ListAttachmentsForOption :many
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments
WHERE slot_option_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsForOption(ctx context.Context, slotOptionID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForOption, slotOptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.BudgetEntryID,
			&i.SlotID,
			&i.Kind,
			&i.Status,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OriginalName,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForSlot = `-- name: ListAttachmentsForSlot :many
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments
WHERE slot_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsForSlot(ctx context.Context, slotID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.BudgetEntryID,
			&i.SlotID,
			&i.Kind,
			&i.Status,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OriginalName,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForTrip = `-- name: ListAttachmentsForTrip :many
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

// The resync-comparison path: every live attachment in a trip in one indexed lookup.
func (q *Queries) ListAttachmentsForTrip(ctx context.Context, tripID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.BudgetEntryID,
			&i.SlotID,
			&i.Kind,
			&i.Status,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OriginalName,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingAttachments = `-- name: ListStalePendingAttachments :many
SELECT id, trip_id, slot_option_id, budget_entry_id, slot_id, kind, status, storage_key, external_url, content_type, size_bytes, checksum_sha256, original_name, uploaded_by, created_at, updated_at, deleted_at FROM attachments
WHERE status = 'pending' AND created_at < $1 AND deleted_at IS NULL
ORDER BY created_at
LIMIT $2
`

type ListStalePendingAttachmentsParams struct {
	Before   time.Time
	RowLimit int32
}

// Drives the sweeper for uploads that were presigned and then abandoned. Served by the partial
// index attachments_pending, so the scan cost is proportional to the number of pending rows
// rather than to the table.
func (q *Queries) ListStalePendingAttachments(ctx context.Context, arg ListStalePendingAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listStalePendingAttachments, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.BudgetEntryID,
			&i.SlotID,
			&i.Kind,
			&i.Status,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OriginalName,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentFailed = `-- name: MarkAttachmentFailed :execrows
UPDATE attachments
SET status     = 'failed',
    updated_at = $1
WHERE id = $2 AND status = 'pending' AND deleted_at IS NULL
`

type MarkAttachmentFailedParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

// Verification rejected the object (too large, wrong type). The row is kept rather than
// deleted so the uploader can be told why, and the sweeper's pending filter no longer matches
// it.
func (q *Queries) MarkAttachmentFailed(ctx context.Context, arg MarkAttachmentFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAttachmentFailed, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :execrows
UPDATE attachments
SET deleted_at = $1,
    updated_at = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteAttachmentParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
}

// No version predicate, because attachments have no version column (D46). Deleting an already
// deleted attachment affects zero rows, which the caller reads as "already gone" rather than
// as a conflict — there is no concurrent-edit case to distinguish it from.
func (q *Queries) SoftDeleteAttachment(ctx context.Context, arg SoftDeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAttachment, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
