// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const budgetEntryExists = `-- name: BudgetEntryExists :one
SELECT EXISTS (SELECT 1 FROM budget_entries WHERE id = $1)
`

func (q *Queries) BudgetEntryExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, budgetEntryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBudgetEntry = `-- name: CreateBudgetEntry :one

INSERT INTO budget_entries (
  id, trip_id, slot_option_id, label, category, amount_minor, paid_by, incurred_on, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, trip_id, slot_option_id, label, category, amount_minor, paid_by, incurred_on, created_by, version, created_at, updated_at, deleted_at
`

type CreateBudgetEntryParams struct {
	ID           uuid.UUID
	TripID       uuid.UUID
	SlotOptionID *uuid.UUID
	Label        string
	Category     string
	AmountMinor  int64
	PaidBy       *uuid.UUID
	IncurredOn   *time.Time
	CreatedBy    *uuid.UUID
}

// Queries for budget_entries and budget_splits — the trip ledger.
//
// The shape of this file is dictated by D44: an entry and its COMPLETE split set are one
// atomic unit. There is deliberately no UpdateBudgetSplit and no DeleteBudgetSplit. The only
// way to change a split is to rewrite the whole set alongside its entry, inside one
// transaction, which is what makes the sum invariant enforceable rather than merely checked.
//
// The deferred constraint trigger in migration 000003 is the backstop: splits are rewritten by
// deleting and reinserting, so the invariant is legitimately violated mid-transaction and is
// only checked at COMMIT. That is why DeleteSplitsForEntry followed by InsertBudgetSplit is
// safe here and would not be against an immediate constraint.
func (q *Queries) CreateBudgetEntry(ctx context.Context, arg CreateBudgetEntryParams) (BudgetEntry, error) {
	row := q.db.QueryRow(ctx, createBudgetEntry,
		arg.ID,
		arg.TripID,
		arg.SlotOptionID,
		arg.Label,
		arg.Category,
		arg.AmountMinor,
		arg.PaidBy,
		arg.IncurredOn,
		arg.CreatedBy,
	)
	var i BudgetEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.Label,
		&i.Category,
		&i.AmountMinor,
		&i.PaidBy,
		&i.IncurredOn,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSplitsForEntry = `-- name: DeleteSplitsForEntry :exec
DELETE FROM budget_splits WHERE budget_entry_id = $1
`

// Half of a rewrite, never a standalone operation. Called only by BudgetRepository.Save, which
// refuses to run outside a transaction precisely so this cannot commit on its own and leave an
// entry with no splits.
func (q *Queries) DeleteSplitsForEntry(ctx context.Context, budgetEntryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSplitsForEntry, budgetEntryID)
	return err
}

const getBudgetEntryByID = `-- name: GetBudgetEntryByID :one
SELECT id, trip_id, slot_option_id, label, category, amount_minor, paid_by, incurred_on, created_by, version, created_at, updated_at, deleted_at FROM budget_entries WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBudgetEntryByID(ctx context.Context, id uuid.UUID) (BudgetEntry, error) {
	row := q.db.QueryRow(ctx, getBudgetEntryByID, id)
	var i BudgetEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.Label,
		&i.Category,
		&i.AmountMinor,
		&i.PaidBy,
		&i.IncurredOn,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertBudgetSplit = `-- name: InsertBudgetSplit :one
INSERT INTO budget_splits (id, budget_entry_id, user_id, amount_minor)
VALUES ($1, $2, $3, $4)
RETURNING id, budget_entry_id, user_id, amount_minor, created_at
`

type InsertBudgetSplitParams struct {
	ID            uuid.UUID
	BudgetEntryID uuid.UUID
	UserID        uuid.UUID
	AmountMinor   int64
}

func (q *Queries) InsertBudgetSplit(ctx context.Context, arg InsertBudgetSplitParams) (BudgetSplit, error) {
	row := q.db.QueryRow(ctx, insertBudgetSplit,
		arg.ID,
		arg.BudgetEntryID,
		arg.UserID,
		arg.AmountMinor,
	)
	var i BudgetSplit
	err := row.Scan(
		&i.ID,
		&i.BudgetEntryID,
		&i.UserID,
		&i.AmountMinor,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgetEntriesForTrip = `-- name: ListBudgetEntriesForTrip :many
SELECT id, trip_id, slot_option_id, label, category, amount_minor, paid_by, incurred_on, created_by, version, created_at, updated_at, deleted_at FROM budget_entries
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY incurred_on ASC NULLS LAST, created_at, id
`

// Ordered by the date the cost was incurred, then by creation, so a ledger reads
// chronologically. NULLS LAST keeps entries with no date from leading the list. The id
// tiebreak keeps the order total.
func (q *Queries) ListBudgetEntriesForTrip(ctx context.Context, tripID uuid.UUID) ([]BudgetEntry, error) {
	rows, err := q.db.Query(ctx, listBudgetEntriesForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetEntry{}
	for rows.Next() {
		var i BudgetEntry
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.SlotOptionID,
			&i.Label,
			&i.Category,
			&i.AmountMinor,
			&i.PaidBy,
			&i.IncurredOn,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsForEntry = `-- name: ListSplitsForEntry :many
SELECT id, budget_entry_id, user_id, amount_minor, created_at FROM budget_splits WHERE budget_entry_id = $1 ORDER BY user_id
`

// Ordered by user id, matching the canonical order the operation log uses (domain.splitValues).
// Two representations of one split set that sort differently would make every
// fold(log) == database comparison order-sensitive.
func (q *Queries) ListSplitsForEntry(ctx context.Context, budgetEntryID uuid.UUID) ([]BudgetSplit, error) {
	rows, err := q.db.Query(ctx, listSplitsForEntry, budgetEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetSplit{}
	for rows.Next() {
		var i BudgetSplit
		if err := rows.Scan(
			&i.ID,
			&i.BudgetEntryID,
			&i.UserID,
			&i.AmountMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsForTrip = `-- name: ListSplitsForTrip :many
SELECT s.id, s.budget_entry_id, s.user_id, s.amount_minor, s.created_at FROM budget_splits s
JOIN budget_entries e ON e.id = s.budget_entry_id
WHERE e.trip_id = $1 AND e.deleted_at IS NULL
ORDER BY s.budget_entry_id, s.user_id
`

// Loads every split for a trip in one query, so listing a ledger costs two round trips rather
// than one per entry. Joined rather than passed an id array because the entry filter and the
// soft-delete filter must agree with ListBudgetEntriesForTrip exactly.
func (q *Queries) ListSplitsForTrip(ctx context.Context, tripID uuid.UUID) ([]BudgetSplit, error) {
	rows, err := q.db.Query(ctx, listSplitsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetSplit{}
	for rows.Next() {
		var i BudgetSplit
		if err := rows.Scan(
			&i.ID,
			&i.BudgetEntryID,
			&i.UserID,
			&i.AmountMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBudgetEntry = `-- name: SoftDeleteBudgetEntry :execrows
UPDATE budget_entries
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteBudgetEntryParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) SoftDeleteBudgetEntry(ctx context.Context, arg SoftDeleteBudgetEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBudgetEntry, arg.DeletedAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBudgetEntry = `-- name: UpdateBudgetEntry :one
UPDATE budget_entries
SET slot_option_id = $1,
    label          = $2,
    category       = $3,
    amount_minor   = $4,
    paid_by        = $5,
    incurred_on    = $6,
    version        = version + 1,
    updated_at     = $7
WHERE id = $8 AND version = $9 AND deleted_at IS NULL
RETURNING id, trip_id, slot_option_id, label, category, amount_minor, paid_by, incurred_on, created_by, version, created_at, updated_at, deleted_at
`

type UpdateBudgetEntryParams struct {
	SlotOptionID *uuid.UUID
	Label        string
	Category     string
	AmountMinor  int64
	PaidBy       *uuid.UUID
	IncurredOn   *time.Time
	UpdatedAt    time.Time
	ID           uuid.UUID
	Version      int32
}

// Optimistic, and the version is NEVER optional for a budget write (D85). Where a slot merges
// field by field and can therefore substitute the version it just read, an entry is replaced
// whole — so a caller without a version is asking to overwrite numbers it has not seen.
func (q *Queries) UpdateBudgetEntry(ctx context.Context, arg UpdateBudgetEntryParams) (BudgetEntry, error) {
	row := q.db.QueryRow(ctx, updateBudgetEntry,
		arg.SlotOptionID,
		arg.Label,
		arg.Category,
		arg.AmountMinor,
		arg.PaidBy,
		arg.IncurredOn,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i BudgetEntry
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.SlotOptionID,
		&i.Label,
		&i.Category,
		&i.AmountMinor,
		&i.PaidBy,
		&i.IncurredOn,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
