// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one

INSERT INTO comments (id, slot_id, trip_id, body, author_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slot_id, trip_id, body, author_id, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	ID       uuid.UUID
	SlotID   uuid.UUID
	TripID   uuid.UUID
	Body     string
	AuthorID *uuid.UUID
}

// Queries for comments — flat, per-slot discussion.
//
// Note what is absent: there is no UpdateComment. Comments are append-only (D46-style, decided
// before migration 000005 was written) — post a new one, delete the old one. The only two
// statements a comment's life ever needs are the insert and the tombstone below.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.SlotID,
		arg.TripID,
		arg.Body,
		arg.AuthorID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, slot_id, trip_id, body, author_id, created_at, updated_at, deleted_at FROM comments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommentsForSlot = `-- name: ListCommentsForSlot :many
SELECT id, slot_id, trip_id, body, author_id, created_at, updated_at, deleted_at FROM comments
WHERE slot_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListCommentsForSlot(ctx context.Context, slotID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.TripID,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments
SET deleted_at = $1,
    updated_at = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteCommentParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
}

// No version predicate, because comments have no version column (D46-style). Deleting an
// already-deleted comment affects zero rows, read as "already gone" — there is no
// concurrent-edit case to distinguish it from, since there is no edit at all.
func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComment, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
