// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: days.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDay = `-- name: CreateDay :one

INSERT INTO days (id, trip_id, date, label, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trip_id, date, label, position, version, created_at, updated_at, deleted_at
`

type CreateDayParams struct {
	ID       uuid.UUID
	TripID   uuid.UUID
	Date     *time.Time
	Label    string
	Position string
}

// Queries for days.
func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) (Day, error) {
	row := q.db.QueryRow(ctx, createDay,
		arg.ID,
		arg.TripID,
		arg.Date,
		arg.Label,
		arg.Position,
	)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.Label,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const dayExists = `-- name: DayExists :one
SELECT EXISTS (SELECT 1 FROM days WHERE id = $1)
`

func (q *Queries) DayExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, dayExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dayPositionAfter = `-- name: DayPositionAfter :one
SELECT position FROM days
WHERE trip_id = $1
  AND deleted_at IS NULL
  -- See items.sql: sqlc cannot infer parameter types inside a row comparison, so the casts
  -- are what keep @after_id typed as a UUID in the generated Go.
  AND (position, id) > ($2::text, $3::uuid)
ORDER BY position, id
LIMIT 1
`

type DayPositionAfterParams struct {
	TripID        uuid.UUID
	AfterPosition string
	AfterID       uuid.UUID
}

// The position of the day immediately following the given (position, id). Comparing the
// tuple keeps this consistent with the ORDER BY above; comparing position alone would skip
// or repeat rows whenever two days share a position.
func (q *Queries) DayPositionAfter(ctx context.Context, arg DayPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, dayPositionAfter, arg.TripID, arg.AfterPosition, arg.AfterID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const firstDayPosition = `-- name: FirstDayPosition :one
SELECT position FROM days
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY position, id
LIMIT 1
`

func (q *Queries) FirstDayPosition(ctx context.Context, tripID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, firstDayPosition, tripID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getDayByID = `-- name: GetDayByID :one
SELECT id, trip_id, date, label, position, version, created_at, updated_at, deleted_at FROM days WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDayByID(ctx context.Context, id uuid.UUID) (Day, error) {
	row := q.db.QueryRow(ctx, getDayByID, id)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.Label,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDayPosition = `-- name: GetDayPosition :one
SELECT position FROM days WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDayPosition(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDayPosition, id)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listDaysForTrip = `-- name: ListDaysForTrip :many
SELECT id, trip_id, date, label, position, version, created_at, updated_at, deleted_at FROM days
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

// Ordered by (position, id). The id tiebreak is not cosmetic: two clients inserting into
// the same gap without seeing each other legitimately produce the SAME fractional index,
// and the id is what makes every replica derive an identical total order from that.
func (q *Queries) ListDaysForTrip(ctx context.Context, tripID uuid.UUID) ([]Day, error) {
	rows, err := q.db.Query(ctx, listDaysForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Day{}
	for rows.Next() {
		var i Day
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Date,
			&i.Label,
			&i.Position,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDay = `-- name: SoftDeleteDay :execrows
UPDATE days
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteDayParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) SoftDeleteDay(ctx context.Context, arg SoftDeleteDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDay, arg.DeletedAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDay = `-- name: UpdateDay :one
UPDATE days
SET date       = $1,
    label      = $2,
    position   = $3,
    version    = version + 1,
    updated_at = $4
WHERE id = $5 AND version = $6 AND deleted_at IS NULL
RETURNING id, trip_id, date, label, position, version, created_at, updated_at, deleted_at
`

type UpdateDayParams struct {
	Date      *time.Time
	Label     string
	Position  string
	UpdatedAt time.Time
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) UpdateDay(ctx context.Context, arg UpdateDayParams) (Day, error) {
	row := q.db.QueryRow(ctx, updateDay,
		arg.Date,
		arg.Label,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Date,
		&i.Label,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
