// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO trip_invitations (id, trip_id, email, role, token_hash, created_by, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, trip_id, email, role, token_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Email     *string
	Role      string
	TokenHash []byte
	CreatedBy uuid.UUID
	MaxUses   *int32
	ExpiresAt time.Time
}

// Queries for trip_invitations.
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TripInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.TripID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i TripInvitation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByHash = `-- name: GetInvitationByHash :one
SELECT id, trip_id, email, role, token_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at FROM trip_invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByHash(ctx context.Context, tokenHash []byte) (TripInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByHash, tokenHash)
	var i TripInvitation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsForTrip = `-- name: ListInvitationsForTrip :many
SELECT id, trip_id, email, role, token_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at FROM trip_invitations
WHERE trip_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsForTrip(ctx context.Context, tripID uuid.UUID) ([]TripInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripInvitation{}
	for rows.Next() {
		var i TripInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvitation = `-- name: RedeemInvitation :one
UPDATE trip_invitations
SET use_count = use_count + 1
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND (max_uses IS NULL OR use_count < max_uses)
RETURNING id, trip_id, email, role, token_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at
`

type RedeemInvitationParams struct {
	ID  uuid.UUID
	Now time.Time
}

// Atomic redemption. Every condition that makes an invitation usable is checked in the SAME
// statement that consumes a use, so a single-use link cannot be redeemed twice by two
// concurrent requests.
//
// The read-then-write alternative is a textbook race: both requests read use_count = 0,
// both conclude the link is valid, both increment, and two people join on a one-use invite.
// Returning zero rows here IS the rejection — the caller does not need a prior check, and
// must not add one.
func (q *Queries) RedeemInvitation(ctx context.Context, arg RedeemInvitationParams) (TripInvitation, error) {
	row := q.db.QueryRow(ctx, redeemInvitation, arg.ID, arg.Now)
	var i TripInvitation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE trip_invitations SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	RevokedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
