// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one

INSERT INTO trip_members (id, trip_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trip_id, user_id, role, invited_by, joined_at, version, created_at, updated_at, deleted_at
`

type AddMemberParams struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	InvitedBy *uuid.UUID
}

// Queries for trip_members.
//
// This is the core/domain seam. The MembershipRepository interface these back is
// module-agnostic and a second module would satisfy it with its own table; the table itself
// is not shared, so Postgres can still enforce referential integrity.
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.ID,
		arg.TripID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countMembersByRole = `-- name: CountMembersByRole :one
SELECT count(*) FROM trip_members
WHERE trip_id = $1 AND role = $2 AND deleted_at IS NULL
`

type CountMembersByRoleParams struct {
	TripID uuid.UUID
	Role   string
}

func (q *Queries) CountMembersByRole(ctx context.Context, arg CountMembersByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByRole, arg.TripID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMember = `-- name: GetMember :one
SELECT id, trip_id, user_id, role, invited_by, joined_at, version, created_at, updated_at, deleted_at FROM trip_members
WHERE trip_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetMemberParams struct {
	TripID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.TripID, arg.UserID)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMemberProfiles = `-- name: ListMemberProfiles :many
SELECT m.id, m.trip_id, m.user_id, m.role, m.invited_by, m.joined_at, m.version, m.created_at, m.updated_at, m.deleted_at, u.display_name
FROM trip_members m
JOIN users u ON u.id = m.user_id
WHERE m.trip_id = $1 AND m.deleted_at IS NULL
ORDER BY (m.role = 'owner') DESC, m.joined_at ASC
`

type ListMemberProfilesRow struct {
	ID          uuid.UUID
	TripID      uuid.UUID
	UserID      uuid.UUID
	Role        string
	InvitedBy   *uuid.UUID
	JoinedAt    time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DisplayName string
}

// The member list AS RENDERED: membership plus the one user field every collaborative
// surface needs to show a person rather than a UUID.
//
// A read model, deliberately separate from ListMembers rather than replacing it. Membership
// is an authorization fact and is read on the hot path by every authz check; joining users
// there would tax that path to serve a screen. Email is NOT selected — display name is
// enough to render an author, a voter or a split, and broadcasting everyone's address to
// every viewer is a disclosure the UI does not need (the D53 instinct, one level down).
func (q *Queries) ListMemberProfiles(ctx context.Context, tripID uuid.UUID) ([]ListMemberProfilesRow, error) {
	rows, err := q.db.Query(ctx, listMemberProfiles, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberProfilesRow{}
	for rows.Next() {
		var i ListMemberProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, trip_id, user_id, role, invited_by, joined_at, version, created_at, updated_at, deleted_at FROM trip_members
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY (role = 'owner') DESC, joined_at ASC
`

// Owner first, then by join order: the list is almost always rendered as-is, and the owner
// is the entry people look for.
func (q *Queries) ListMembers(ctx context.Context, tripID uuid.UUID) ([]TripMember, error) {
	rows, err := q.db.Query(ctx, listMembers, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripMember{}
	for rows.Next() {
		var i TripMember
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExists = `-- name: MemberExists :one
SELECT EXISTS (
  SELECT 1 FROM trip_members WHERE trip_id = $1 AND user_id = $2
)
`

type MemberExistsParams struct {
	TripID uuid.UUID
	UserID uuid.UUID
}

// Ignores deleted_at so a zero-row update can be attributed to a version conflict rather
// than a missing row.
func (q *Queries) MemberExists(ctx context.Context, arg MemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberExists, arg.TripID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeMember = `-- name: RemoveMember :execrows
UPDATE trip_members
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE trip_id = $2 AND user_id = $3 AND deleted_at IS NULL
`

type RemoveMemberParams struct {
	DeletedAt *time.Time
	TripID    uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.DeletedAt, arg.TripID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE trip_members
SET role       = $1,
    version    = version + 1,
    updated_at = $2
WHERE trip_id = $3 AND user_id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, trip_id, user_id, role, invited_by, joined_at, version, created_at, updated_at, deleted_at
`

type UpdateMemberRoleParams struct {
	Role      string
	UpdatedAt time.Time
	TripID    uuid.UUID
	UserID    uuid.UUID
	Version   int32
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (TripMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole,
		arg.Role,
		arg.UpdatedAt,
		arg.TripID,
		arg.UserID,
		arg.Version,
	)
	var i TripMember
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
