// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID             uuid.UUID
	TripID         uuid.UUID
	SlotOptionID   *uuid.UUID
	BudgetEntryID  *uuid.UUID
	SlotID         *uuid.UUID
	Kind           string
	Status         string
	StorageKey     string
	ExternalUrl    string
	ContentType    string
	SizeBytes      *int64
	ChecksumSha256 []byte
	OriginalName   string
	UploadedBy     *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type AuthSession struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	UserAgent     string
	Ip            *netip.Addr
	CreatedAt     time.Time
	LastUsedAt    time.Time
	ExpiresAt     time.Time
	RevokedAt     *time.Time
	RevokedReason *string
}

type BudgetEntry struct {
	ID           uuid.UUID
	TripID       uuid.UUID
	SlotOptionID *uuid.UUID
	Label        string
	Category     string
	AmountMinor  int64
	PaidBy       *uuid.UUID
	IncurredOn   *time.Time
	CreatedBy    *uuid.UUID
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type BudgetSplit struct {
	ID            uuid.UUID
	BudgetEntryID uuid.UUID
	UserID        uuid.UUID
	AmountMinor   int64
	CreatedAt     time.Time
}

type Comment struct {
	ID        uuid.UUID
	SlotID    uuid.UUID
	TripID    uuid.UUID
	Body      string
	AuthorID  *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Day struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Date      *time.Time
	Label     string
	Position  string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type OptionVote struct {
	ID        uuid.UUID
	SlotID    uuid.UUID
	TripID    uuid.UUID
	UserID    uuid.UUID
	OptionID  *uuid.UUID
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	SessionID  uuid.UUID
	TokenHash  []byte
	IssuedAt   time.Time
	ExpiresAt  time.Time
	UsedAt     *time.Time
	ReplacedBy *uuid.UUID
}

type Slot struct {
	ID               uuid.UUID
	TripID           uuid.UUID
	DayID            *uuid.UUID
	Kind             string
	Title            string
	Notes            string
	StartTime        pgtype.Time
	EndTime          pgtype.Time
	Position         string
	SelectedOptionID *uuid.UUID
	Status           string
	StatusChangedAt  *time.Time
	StatusChangedBy  *uuid.UUID
	CreatedBy        *uuid.UUID
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}

type SlotOption struct {
	ID                 uuid.UUID
	SlotID             uuid.UUID
	TripID             uuid.UUID
	Title              string
	Notes              string
	ExternalUrl        string
	EstimatedCostMinor *int64
	PlaceName          string
	PlaceAddress       string
	PlaceLat           *float64
	PlaceLng           *float64
	PlaceProviderID    string
	ProposedBy         *uuid.UUID
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type Trip struct {
	ID           uuid.UUID
	Name         string
	Description  string
	StartDate    *time.Time
	EndDate      *time.Time
	TimeZone     string
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	BaseCurrency string
	OpSeq        int64
}

type TripInvitation struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Email     *string
	Role      string
	TokenHash []byte
	CreatedBy uuid.UUID
	MaxUses   *int32
	UseCount  int32
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type TripMember struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	InvitedBy *uuid.UUID
	JoinedAt  time.Time
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type TripOp struct {
	ID         uuid.UUID
	TripID     uuid.UUID
	Seq        int64
	ActorID    *uuid.UUID
	Kind       string
	EntityID   uuid.UUID
	Fields     []string
	Payload    []byte
	ClientOpID *uuid.UUID
	CauseOpID  *uuid.UUID
	CreatedAt  time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt *time.Time
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type UserToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Purpose    string
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}
