// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const appendOp = `-- name: AppendOp :one
INSERT INTO trip_ops (id, trip_id, seq, actor_id, kind, entity_id, fields, payload,
                      client_op_id, cause_op_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10)
RETURNING id, trip_id, seq, actor_id, kind, entity_id, fields, payload, client_op_id, cause_op_id, created_at
`

type AppendOpParams struct {
	ID         uuid.UUID
	TripID     uuid.UUID
	Seq        int64
	ActorID    *uuid.UUID
	Kind       string
	EntityID   uuid.UUID
	Fields     []string
	Payload    []byte
	ClientOpID *uuid.UUID
	CauseOpID  *uuid.UUID
}

// Writes one committed operation. Must run in the same transaction as the mutation it
// records — that co-location is what makes "everything since seq N" complete for REST and
// WebSocket writes alike.
func (q *Queries) AppendOp(ctx context.Context, arg AppendOpParams) (TripOp, error) {
	row := q.db.QueryRow(ctx, appendOp,
		arg.ID,
		arg.TripID,
		arg.Seq,
		arg.ActorID,
		arg.Kind,
		arg.EntityID,
		arg.Fields,
		arg.Payload,
		arg.ClientOpID,
		arg.CauseOpID,
	)
	var i TripOp
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Seq,
		&i.ActorID,
		&i.Kind,
		&i.EntityID,
		&i.Fields,
		&i.Payload,
		&i.ClientOpID,
		&i.CauseOpID,
		&i.CreatedAt,
	)
	return i, err
}

const currentOpSeq = `-- name: CurrentOpSeq :one
SELECT op_seq FROM trips WHERE id = $1 AND deleted_at IS NULL
`

// Where a room currently is, for a subscriber establishing its starting point. No lock.
func (q *Queries) CurrentOpSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, currentOpSeq, id)
	var op_seq int64
	err := row.Scan(&op_seq)
	return op_seq, err
}

const getOpByClientOpID = `-- name: GetOpByClientOpID :one
SELECT id, trip_id, seq, actor_id, kind, entity_id, fields, payload, client_op_id, cause_op_id, created_at FROM trip_ops WHERE trip_id = $1 AND client_op_id = $2
`

type GetOpByClientOpIDParams struct {
	TripID     uuid.UUID
	ClientOpID *uuid.UUID
}

// Idempotent replay. A client that sent an operation, lost the connection before the
// acknowledgement, and retried must receive the operation it already committed rather than
// commit a second one — field-mask sets happen to be idempotent, but creates and cascades are
// not.
func (q *Queries) GetOpByClientOpID(ctx context.Context, arg GetOpByClientOpIDParams) (TripOp, error) {
	row := q.db.QueryRow(ctx, getOpByClientOpID, arg.TripID, arg.ClientOpID)
	var i TripOp
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Seq,
		&i.ActorID,
		&i.Kind,
		&i.EntityID,
		&i.Fields,
		&i.Payload,
		&i.ClientOpID,
		&i.CauseOpID,
		&i.CreatedAt,
	)
	return i, err
}

const listOpsSince = `-- name: ListOpsSince :many
SELECT id, trip_id, seq, actor_id, kind, entity_id, fields, payload, client_op_id, cause_op_id, created_at FROM trip_ops
WHERE trip_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListOpsSinceParams struct {
	TripID    uuid.UUID
	AfterSeq  int64
	PageLimit int32
}

// The resync scan, and the only query shape this table serves.
//
// Note what makes this a range scan rather than a re-fetch: there is exactly ONE sequencer per
// trip, so a client's complete sync state is the single integer @after_seq. No per-actor
// vector, no per-entity clocks — the version vector for a room is one number.
func (q *Queries) ListOpsSince(ctx context.Context, arg ListOpsSinceParams) ([]TripOp, error) {
	rows, err := q.db.Query(ctx, listOpsSince, arg.TripID, arg.AfterSeq, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripOp{}
	for rows.Next() {
		var i TripOp
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Seq,
			&i.ActorID,
			&i.Kind,
			&i.EntityID,
			&i.Fields,
			&i.Payload,
			&i.ClientOpID,
			&i.CauseOpID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTripForWrite = `-- name: LockTripForWrite :one

SELECT id FROM trips WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

// Queries for the operation log and the per-trip sequencer.
//
// There is deliberately NO update and NO delete against trip_ops. The log is immutable, and
// immutability here is enforced by the absence of the SQL that would break it (plus an
// assertion in tests/schema_verify.sql), not by asking people not to write it.
// The FIRST statement of every write transaction in a trip (D60).
//
// SELECT ... FOR UPDATE takes the trip's row lock, serializing every writer in that trip
// BEFORE any of them reads an entity. That ordering is the entire conflict model: it makes
// read-modify-write safe (so the whole Stage 1 repository layer is reused unchanged), and it
// makes field-level merge fall out of "an operation writes only the columns it names".
//
// Taking this lock AFTER the read instead would let two transactions read the same slot state
// concurrently and serialize only when they allocated their sequence numbers — a lost update
// at field granularity, with a log that still looked perfectly ordered. That is the subtlest
// available way to break this design.
//
// It doubles as the trip's existence-and-not-deleted check, so callers get ErrNotFound for a
// deleted trip before doing any work.
func (q *Queries) LockTripForWrite(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockTripForWrite, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const nextOpSeq = `-- name: NextOpSeq :one
UPDATE trips SET op_seq = op_seq + 1 WHERE id = $1 RETURNING op_seq
`

// Allocates the next sequence number.
//
// A counter column rather than a Postgres SEQUENCE (D61): a sequence is non-transactional, so
// a rolled-back transaction burns its number and gaps the log. This rolls back with everything
// else, which is what lets a client treat seq contiguity as a completeness check.
//
// Deliberately touches op_seq ONLY — not version, not updated_at. Bumping the trip's version
// on every slot edit would invalidate every REST client's cached trip version and produce
// spurious 409s on unrelated trip updates.
func (q *Queries) NextOpSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextOpSeq, id)
	var op_seq int64
	err := row.Scan(&op_seq)
	return op_seq, err
}
