// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: options.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLiveOptionsForSlot = `-- name: CountLiveOptionsForSlot :one
SELECT count(*) FROM slot_options WHERE slot_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveOptionsForSlot(ctx context.Context, slotID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveOptionsForSlot, slotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSlotOption = `-- name: CreateSlotOption :one

INSERT INTO slot_options (
  id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor,
  place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13
)
RETURNING id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor, place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by, version, created_at, updated_at, deleted_at
`

type CreateSlotOptionParams struct {
	ID                 uuid.UUID
	SlotID             uuid.UUID
	TripID             uuid.UUID
	Title              string
	Notes              string
	ExternalUrl        string
	EstimatedCostMinor *int64
	PlaceName          string
	PlaceAddress       string
	PlaceLat           *float64
	PlaceLng           *float64
	PlaceProviderID    string
	ProposedBy         *uuid.UUID
}

// Queries for slot_options — the candidate proposals under a slot.
func (q *Queries) CreateSlotOption(ctx context.Context, arg CreateSlotOptionParams) (SlotOption, error) {
	row := q.db.QueryRow(ctx, createSlotOption,
		arg.ID,
		arg.SlotID,
		arg.TripID,
		arg.Title,
		arg.Notes,
		arg.ExternalUrl,
		arg.EstimatedCostMinor,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceLat,
		arg.PlaceLng,
		arg.PlaceProviderID,
		arg.ProposedBy,
	)
	var i SlotOption
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.ExternalUrl,
		&i.EstimatedCostMinor,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceLat,
		&i.PlaceLng,
		&i.PlaceProviderID,
		&i.ProposedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSlotOptionByID = `-- name: GetSlotOptionByID :one
SELECT id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor, place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by, version, created_at, updated_at, deleted_at FROM slot_options WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSlotOptionByID(ctx context.Context, id uuid.UUID) (SlotOption, error) {
	row := q.db.QueryRow(ctx, getSlotOptionByID, id)
	var i SlotOption
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.ExternalUrl,
		&i.EstimatedCostMinor,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceLat,
		&i.PlaceLng,
		&i.PlaceProviderID,
		&i.ProposedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOptionsForSlot = `-- name: ListOptionsForSlot :many
SELECT id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor, place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by, version, created_at, updated_at, deleted_at FROM slot_options
WHERE slot_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

// Ordered by creation, not by a fractional index. Reordering candidates is not a gesture the
// product needs; if it becomes one, the position scheme applies identically as an added
// column. The id tiebreak keeps the order total when two options share a timestamp.
func (q *Queries) ListOptionsForSlot(ctx context.Context, slotID uuid.UUID) ([]SlotOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlotOption{}
	for rows.Next() {
		var i SlotOption
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.TripID,
			&i.Title,
			&i.Notes,
			&i.ExternalUrl,
			&i.EstimatedCostMinor,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceLat,
			&i.PlaceLng,
			&i.PlaceProviderID,
			&i.ProposedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsForTrip = `-- name: ListOptionsForTrip :many
SELECT id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor, place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by, version, created_at, updated_at, deleted_at FROM slot_options
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY slot_id, created_at, id
`

// The Stage 2 resync path: every option in a sync room, in one indexed lookup with no join.
// This is what the denormalised trip_id buys.
func (q *Queries) ListOptionsForTrip(ctx context.Context, tripID uuid.UUID) ([]SlotOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlotOption{}
	for rows.Next() {
		var i SlotOption
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.TripID,
			&i.Title,
			&i.Notes,
			&i.ExternalUrl,
			&i.EstimatedCostMinor,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceLat,
			&i.PlaceLng,
			&i.PlaceProviderID,
			&i.ProposedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slotOptionExists = `-- name: SlotOptionExists :one
SELECT EXISTS (SELECT 1 FROM slot_options WHERE id = $1)
`

func (q *Queries) SlotOptionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, slotOptionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSlotOption = `-- name: SoftDeleteSlotOption :execrows
UPDATE slot_options
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteSlotOptionParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
	Version   int32
}

// Tombstoned, like a slot. Note what the schema does on top of this: if the deleted option
// was the slot's selection, slots.selected_option_id is NOT cleared here, because a soft
// delete leaves the row present and the FK satisfied. Clearing a stale selection is a
// service-layer decision, made explicitly rather than as a side effect of a DELETE.
func (q *Queries) SoftDeleteSlotOption(ctx context.Context, arg SoftDeleteSlotOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSlotOption, arg.DeletedAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSlotOption = `-- name: UpdateSlotOption :one
UPDATE slot_options
SET title                = $1,
    notes                = $2,
    external_url         = $3,
    estimated_cost_minor = $4,
    place_name           = $5,
    place_address        = $6,
    place_lat            = $7,
    place_lng            = $8,
    place_provider_id    = $9,
    version              = version + 1,
    updated_at           = $10
WHERE id = $11 AND version = $12 AND deleted_at IS NULL
RETURNING id, slot_id, trip_id, title, notes, external_url, estimated_cost_minor, place_name, place_address, place_lat, place_lng, place_provider_id, proposed_by, version, created_at, updated_at, deleted_at
`

type UpdateSlotOptionParams struct {
	Title              string
	Notes              string
	ExternalUrl        string
	EstimatedCostMinor *int64
	PlaceName          string
	PlaceAddress       string
	PlaceLat           *float64
	PlaceLng           *float64
	PlaceProviderID    string
	UpdatedAt          time.Time
	ID                 uuid.UUID
	Version            int32
}

func (q *Queries) UpdateSlotOption(ctx context.Context, arg UpdateSlotOptionParams) (SlotOption, error) {
	row := q.db.QueryRow(ctx, updateSlotOption,
		arg.Title,
		arg.Notes,
		arg.ExternalUrl,
		arg.EstimatedCostMinor,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceLat,
		arg.PlaceLng,
		arg.PlaceProviderID,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i SlotOption
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.Title,
		&i.Notes,
		&i.ExternalUrl,
		&i.EstimatedCostMinor,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceLat,
		&i.PlaceLng,
		&i.PlaceProviderID,
		&i.ProposedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
