// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, session_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, token_hash, issued_at, expires_at, used_at, replaced_by
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO auth_sessions (id, user_id, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, user_agent, ip, created_at, last_used_at, expires_at, revoked_at, revoked_reason
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	UserAgent string
	Ip        *netip.Addr
	ExpiresAt time.Time
}

// Queries for auth_sessions and refresh_tokens.
//
// These two tables are one aggregate. A refresh token is meaningless outside its family,
// and reuse detection has to revoke both together in a single transaction — which is why
// they share one repository rather than being split by table.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

// Relies on refresh_tokens_replaced_by. Without that index this is quadratic: the
// self-referencing FK forces a scan for referring rows per row deleted.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth_sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, session_id, token_hash, issued_at, expires_at, used_at, replaced_by FROM refresh_tokens WHERE token_hash = $1
`

// No expiry or used_at filter here on purpose. An expired or already-used token must still
// be FOUND so the service can tell "unknown token" from "replayed token" — the latter is a
// security signal that revokes the entire family, and filtering it out here would silently
// downgrade a break-in to a routine 401.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, user_agent, ip, created_at, last_used_at, expires_at, revoked_at, revoked_reason FROM auth_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, user_agent, ip, created_at, last_used_at, expires_at, revoked_at, revoked_reason FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > $2
ORDER BY last_used_at DESC
`

type ListActiveSessionsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

// Ordered by most recently used: the session-management UI is answering "what is logged in
// right now", and the answer people scan for first is their current device.
func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE refresh_tokens
SET used_at = $1, replaced_by = $2
WHERE id = $3 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	UsedAt     *time.Time
	ReplacedBy *uuid.UUID
	ID         uuid.UUID
}

// The `used_at IS NULL` guard makes rotation atomic: if two requests race with the same
// token, exactly one updates a row. The loser sees zero rows and is treated as a replay,
// which is the correct conclusion.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.UsedAt, arg.ReplacedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE auth_sessions
SET revoked_at = $1, revoked_reason = $2
WHERE user_id = $3 AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	RevokedAt     *time.Time
	RevokedReason *string
	UserID        uuid.UUID
}

// What a password reset calls. A reset that leaves an attacker's session alive is worse
// than useless.
func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessions, arg.RevokedAt, arg.RevokedReason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE auth_sessions
SET revoked_at = $1, revoked_reason = $2
WHERE id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt     *time.Time
	RevokedReason *string
	ID            uuid.UUID
}

// Idempotent by design: `revoked_at IS NULL` means a double revoke affects zero rows and
// preserves the ORIGINAL reason. That matters because the first reason is the interesting
// one — a session revoked for token reuse must not later be relabelled as a logout.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.RevokedReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE auth_sessions SET last_used_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	LastUsedAt time.Time
	ID         uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
