// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slots.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSlot = `-- name: CreateSlot :one

INSERT INTO slots (
  id, trip_id, day_id, kind, title, notes,
  start_time, end_time, position, status, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11
)
RETURNING id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at
`

type CreateSlotParams struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	DayID     *uuid.UUID
	Kind      string
	Title     string
	Notes     string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Position  string
	Status    string
	CreatedBy *uuid.UUID
}

// Queries for slots — the decisions in an itinerary.
func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.ID,
		arg.TripID,
		arg.DayID,
		arg.Kind,
		arg.Title,
		arg.Notes,
		arg.StartTime,
		arg.EndTime,
		arg.Position,
		arg.Status,
		arg.CreatedBy,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const firstSlotPosition = `-- name: FirstSlotPosition :one
SELECT position FROM slots
WHERE trip_id = $1
  AND day_id IS NOT DISTINCT FROM $2::uuid
  AND deleted_at IS NULL
ORDER BY position, id
LIMIT 1
`

type FirstSlotPositionParams struct {
	TripID uuid.UUID
	DayID  *uuid.UUID
}

// `IS NOT DISTINCT FROM` so one query covers both buckets: a specific day, and the backlog
// where day_id IS NULL (plain `=` never matches NULL). It does mean the day_id filter is
// applied after the trip_id index lookup rather than using slots_day_pos directly — a
// deliberate trade, because a trip holds a few hundred slots at most and the alternative is
// two near-identical queries to maintain.
func (q *Queries) FirstSlotPosition(ctx context.Context, arg FirstSlotPositionParams) (string, error) {
	row := q.db.QueryRow(ctx, firstSlotPosition, arg.TripID, arg.DayID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getSlotByID = `-- name: GetSlotByID :one
SELECT id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at FROM slots WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSlotByID(ctx context.Context, id uuid.UUID) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlotByID, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSlotPosition = `-- name: GetSlotPosition :one
SELECT position FROM slots WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSlotPosition(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getSlotPosition, id)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listBacklogSlots = `-- name: ListBacklogSlots :many
SELECT id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at FROM slots
WHERE trip_id = $1 AND day_id IS NULL AND deleted_at IS NULL
ORDER BY position, id
`

// day_id IS NULL is the unscheduled backlog: decisions not yet placed on a day.
func (q *Queries) ListBacklogSlots(ctx context.Context, tripID uuid.UUID) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listBacklogSlots, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayID,
			&i.Kind,
			&i.Title,
			&i.Notes,
			&i.StartTime,
			&i.EndTime,
			&i.Position,
			&i.SelectedOptionID,
			&i.Status,
			&i.StatusChangedAt,
			&i.StatusChangedBy,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsForDay = `-- name: ListSlotsForDay :many
SELECT id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at FROM slots
WHERE day_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

func (q *Queries) ListSlotsForDay(ctx context.Context, dayID *uuid.UUID) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listSlotsForDay, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayID,
			&i.Kind,
			&i.Title,
			&i.Notes,
			&i.StartTime,
			&i.EndTime,
			&i.Position,
			&i.SelectedOptionID,
			&i.Status,
			&i.StatusChangedAt,
			&i.StatusChangedBy,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsForTrip = `-- name: ListSlotsForTrip :many
SELECT id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at FROM slots
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

func (q *Queries) ListSlotsForTrip(ctx context.Context, tripID uuid.UUID) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listSlotsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayID,
			&i.Kind,
			&i.Title,
			&i.Notes,
			&i.StartTime,
			&i.EndTime,
			&i.Position,
			&i.SelectedOptionID,
			&i.Status,
			&i.StatusChangedAt,
			&i.StatusChangedBy,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSlot = `-- name: MoveSlot :one
UPDATE slots
SET day_id     = $1,
    position   = $2,
    version    = version + 1,
    updated_at = $3
WHERE id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at
`

type MoveSlotParams struct {
	DayID     *uuid.UUID
	Position  string
	UpdatedAt time.Time
	ID        uuid.UUID
	Version   int32
}

// Day and position change together, in one statement, with one version bump.
//
// A move must never be observable as a delete followed by an insert. A client that saw only
// the first half would render the slot as vanished, and in Stage 2 a two-operation move
// would give the sync engine an intermediate state that never actually existed to resolve
// against.
//
// trip_id is deliberately not updatable: slots do not migrate between trips, and the
// composite FK would reject it anyway.
func (q *Queries) MoveSlot(ctx context.Context, arg MoveSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, moveSlot,
		arg.DayID,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setSlotSelectedOption = `-- name: SetSlotSelectedOption :one
UPDATE slots
SET selected_option_id = $1,
    version            = version + 1,
    updated_at         = $2
WHERE id = $3 AND version = $4 AND deleted_at IS NULL
RETURNING id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at
`

type SetSlotSelectedOptionParams struct {
	SelectedOptionID *uuid.UUID
	UpdatedAt        time.Time
	ID               uuid.UUID
	Version          int32
}

// The group's resolution. The composite FK (selected_option_id, id) -> slot_options(id,
// slot_id) means an option belonging to a different slot is rejected by the database, so
// this query does not need to check it.
func (q *Queries) SetSlotSelectedOption(ctx context.Context, arg SetSlotSelectedOptionParams) (Slot, error) {
	row := q.db.QueryRow(ctx, setSlotSelectedOption,
		arg.SelectedOptionID,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setSlotStatus = `-- name: SetSlotStatus :one
UPDATE slots
SET status            = $1,
    status_changed_at = $2,
    status_changed_by = $3,
    version           = version + 1,
    updated_at        = $2
WHERE id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at
`

type SetSlotStatusParams struct {
	Status          string
	StatusChangedAt *time.Time
	StatusChangedBy *uuid.UUID
	ID              uuid.UUID
	Version         int32
}

// Live-mode coverage, recording who and when. A bare enum would throw away the attribution
// that a group arguing about "did we actually do this" wants.
func (q *Queries) SetSlotStatus(ctx context.Context, arg SetSlotStatusParams) (Slot, error) {
	row := q.db.QueryRow(ctx, setSlotStatus,
		arg.Status,
		arg.StatusChangedAt,
		arg.StatusChangedBy,
		arg.ID,
		arg.Version,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const slotExists = `-- name: SlotExists :one
SELECT EXISTS (SELECT 1 FROM slots WHERE id = $1)
`

// Used only to distinguish "not found" from "version conflict" after a zero-row update.
// Deliberately ignores deleted_at: a soft-deleted row still explains why the update missed.
func (q *Queries) SlotExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, slotExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const slotPositionAfter = `-- name: SlotPositionAfter :one
SELECT position FROM slots
WHERE trip_id = $1
  AND day_id IS NOT DISTINCT FROM $2::uuid
  AND deleted_at IS NULL
  -- Casts are required, not decorative: sqlc cannot infer a parameter's type inside a row
  -- comparison and would otherwise type @after_id as text, producing a Go signature that
  -- takes a string where a UUID belongs.
  AND (position, id) > ($3::text, $4::uuid)
ORDER BY position, id
LIMIT 1
`

type SlotPositionAfterParams struct {
	TripID        uuid.UUID
	DayID         *uuid.UUID
	AfterPosition string
	AfterID       uuid.UUID
}

func (q *Queries) SlotPositionAfter(ctx context.Context, arg SlotPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, slotPositionAfter,
		arg.TripID,
		arg.DayID,
		arg.AfterPosition,
		arg.AfterID,
	)
	var position string
	err := row.Scan(&position)
	return position, err
}

const softDeleteSlot = `-- name: SoftDeleteSlot :execrows
UPDATE slots
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteSlotParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
	Version   int32
}

// A tombstone, not a DELETE. Concurrent delete-versus-edit is one of the three required
// Stage 2 conflict cases, and you cannot converge on a row that no longer exists.
func (q *Queries) SoftDeleteSlot(ctx context.Context, arg SoftDeleteSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSlot, arg.DeletedAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSlot = `-- name: UpdateSlot :one
UPDATE slots
SET kind       = $1,
    title      = $2,
    notes      = $3,
    start_time = $4,
    end_time   = $5,
    version    = version + 1,
    updated_at = $6
WHERE id = $7 AND version = $8 AND deleted_at IS NULL
RETURNING id, trip_id, day_id, kind, title, notes, start_time, end_time, position, selected_option_id, status, status_changed_at, status_changed_by, created_by, version, created_at, updated_at, deleted_at
`

type UpdateSlotParams struct {
	Kind      string
	Title     string
	Notes     string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	UpdatedAt time.Time
	ID        uuid.UUID
	Version   int32
}

// Content only. Moving between days or positions goes through MoveSlot; resolving goes
// through SetSlotSelectedOption; coverage goes through SetSlotStatus. Each is a distinct
// operation with distinct authorization, and in Stage 2 a distinct sync operation — merging
// them into one UPDATE would make a content edit indistinguishable from a reorder.
func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, updateSlot,
		arg.Kind,
		arg.Title,
		arg.Notes,
		arg.StartTime,
		arg.EndTime,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayID,
		&i.Kind,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.Position,
		&i.SelectedOptionID,
		&i.Status,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
