// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip_covers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmTripCoverUpload = `-- name: ConfirmTripCoverUpload :execrows
UPDATE trip_cover_uploads
SET status = 'ready', size_bytes = $1, updated_at = $2
WHERE id = $3 AND status = 'pending'
`

type ConfirmTripCoverUploadParams struct {
	SizeBytes *int64
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ConfirmTripCoverUpload(ctx context.Context, arg ConfirmTripCoverUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTripCoverUpload, arg.SizeBytes, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTripCoverUpload = `-- name: CreateTripCoverUpload :one

INSERT INTO trip_cover_uploads (
    id, trip_id, storage_key, content_type, original_name, uploaded_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trip_id, storage_key, content_type, original_name, size_bytes, status, uploaded_by, created_at, updated_at
`

type CreateTripCoverUploadParams struct {
	ID           uuid.UUID
	TripID       uuid.UUID
	StorageKey   string
	ContentType  string
	OriginalName string
	UploadedBy   *uuid.UUID
}

// Upload lifecycle.
func (q *Queries) CreateTripCoverUpload(ctx context.Context, arg CreateTripCoverUploadParams) (TripCoverUpload, error) {
	row := q.db.QueryRow(ctx, createTripCoverUpload,
		arg.ID,
		arg.TripID,
		arg.StorageKey,
		arg.ContentType,
		arg.OriginalName,
		arg.UploadedBy,
	)
	var i TripCoverUpload
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StorageKey,
		&i.ContentType,
		&i.OriginalName,
		&i.SizeBytes,
		&i.Status,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTripCoverUpload = `-- name: FailTripCoverUpload :execrows
UPDATE trip_cover_uploads
SET status = 'failed', updated_at = $1
WHERE id = $2 AND status = 'pending'
`

type FailTripCoverUploadParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) FailTripCoverUpload(ctx context.Context, arg FailTripCoverUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, failTripCoverUpload, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTripCoverSuggestionByID = `-- name: GetTripCoverSuggestionByID :one
SELECT id, query_key, query, found, image_url, photographer_name, photographer_url, photo_url, download_location, expires_at, created_at, updated_at FROM trip_cover_suggestions WHERE id = $1
`

func (q *Queries) GetTripCoverSuggestionByID(ctx context.Context, id uuid.UUID) (TripCoverSuggestion, error) {
	row := q.db.QueryRow(ctx, getTripCoverSuggestionByID, id)
	var i TripCoverSuggestion
	err := row.Scan(
		&i.ID,
		&i.QueryKey,
		&i.Query,
		&i.Found,
		&i.ImageUrl,
		&i.PhotographerName,
		&i.PhotographerUrl,
		&i.PhotoUrl,
		&i.DownloadLocation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripCoverSuggestionByQueryKey = `-- name: GetTripCoverSuggestionByQueryKey :one

SELECT id, query_key, query, found, image_url, photographer_name, photographer_url, photo_url, download_location, expires_at, created_at, updated_at FROM trip_cover_suggestions
WHERE query_key = $1 AND expires_at > $2
`

type GetTripCoverSuggestionByQueryKeyParams struct {
	QueryKey string
	Now      time.Time
}

// Cached destination suggestions.
func (q *Queries) GetTripCoverSuggestionByQueryKey(ctx context.Context, arg GetTripCoverSuggestionByQueryKeyParams) (TripCoverSuggestion, error) {
	row := q.db.QueryRow(ctx, getTripCoverSuggestionByQueryKey, arg.QueryKey, arg.Now)
	var i TripCoverSuggestion
	err := row.Scan(
		&i.ID,
		&i.QueryKey,
		&i.Query,
		&i.Found,
		&i.ImageUrl,
		&i.PhotographerName,
		&i.PhotographerUrl,
		&i.PhotoUrl,
		&i.DownloadLocation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripCoverUploadByID = `-- name: GetTripCoverUploadByID :one
SELECT id, trip_id, storage_key, content_type, original_name, size_bytes, status, uploaded_by, created_at, updated_at FROM trip_cover_uploads WHERE id = $1
`

func (q *Queries) GetTripCoverUploadByID(ctx context.Context, id uuid.UUID) (TripCoverUpload, error) {
	row := q.db.QueryRow(ctx, getTripCoverUploadByID, id)
	var i TripCoverUpload
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StorageKey,
		&i.ContentType,
		&i.OriginalName,
		&i.SizeBytes,
		&i.Status,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTripCoverSuggestion = `-- name: UpsertTripCoverSuggestion :one
INSERT INTO trip_cover_suggestions (
    id, query_key, query, found, image_url, photographer_name, photographer_url,
    photo_url, download_location, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
ON CONFLICT (query_key) DO UPDATE SET
    query = EXCLUDED.query,
    found = EXCLUDED.found,
    image_url = EXCLUDED.image_url,
    photographer_name = EXCLUDED.photographer_name,
    photographer_url = EXCLUDED.photographer_url,
    photo_url = EXCLUDED.photo_url,
    download_location = EXCLUDED.download_location,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id, query_key, query, found, image_url, photographer_name, photographer_url, photo_url, download_location, expires_at, created_at, updated_at
`

type UpsertTripCoverSuggestionParams struct {
	ID               uuid.UUID
	QueryKey         string
	Query            string
	Found            bool
	ImageUrl         string
	PhotographerName string
	PhotographerUrl  string
	PhotoUrl         string
	DownloadLocation string
	ExpiresAt        time.Time
}

func (q *Queries) UpsertTripCoverSuggestion(ctx context.Context, arg UpsertTripCoverSuggestionParams) (TripCoverSuggestion, error) {
	row := q.db.QueryRow(ctx, upsertTripCoverSuggestion,
		arg.ID,
		arg.QueryKey,
		arg.Query,
		arg.Found,
		arg.ImageUrl,
		arg.PhotographerName,
		arg.PhotographerUrl,
		arg.PhotoUrl,
		arg.DownloadLocation,
		arg.ExpiresAt,
	)
	var i TripCoverSuggestion
	err := row.Scan(
		&i.ID,
		&i.QueryKey,
		&i.Query,
		&i.Found,
		&i.ImageUrl,
		&i.PhotographerName,
		&i.PhotographerUrl,
		&i.PhotoUrl,
		&i.DownloadLocation,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
