// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrip = `-- name: CreateTrip :one

INSERT INTO trips (id, name, description, start_date, end_date, time_zone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, start_date, end_date, time_zone, version, created_at, updated_at, deleted_at, base_currency, op_seq
`

type CreateTripParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	StartDate   *time.Time
	EndDate     *time.Time
	TimeZone    string
}

// Queries for trips.
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.TimeZone,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimeZone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BaseCurrency,
		&i.OpSeq,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, name, description, start_date, end_date, time_zone, version, created_at, updated_at, deleted_at, base_currency, op_seq FROM trips WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTripByID(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimeZone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BaseCurrency,
		&i.OpSeq,
	)
	return i, err
}

const listTripsForUser = `-- name: ListTripsForUser :many
SELECT t.id, t.name, t.description, t.start_date, t.end_date, t.time_zone, t.version, t.created_at, t.updated_at, t.deleted_at, t.base_currency, t.op_seq FROM trips t
JOIN trip_members m ON m.trip_id = t.id AND m.deleted_at IS NULL
WHERE m.user_id = $1
  AND t.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (t.created_at, t.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $4
`

type ListTripsForUserParams struct {
	UserID         uuid.UUID
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	PageLimit      int32
}

// Keyset pagination, never OFFSET. Under concurrent inserts — the entire premise of this
// application — OFFSET duplicates and skips rows, because an insert before the current
// offset shifts every subsequent page by one.
//
// The cursor is the row's own (created_at, id). Comparing the tuple rather than the two
// columns separately is what makes the boundary exact: `(a, b) < (x, y)` is a single
// lexicographic comparison, whereas `a < x OR (a = x AND b < y)` is the same thing written
// in a way that is easy to get subtly wrong. id breaks ties so the order is total even when
// two trips share a created_at.
//
// The caller passes limit+1 and trims the probe row; that is how HasMore is determined
// without a second COUNT, which would be both slower and wrong (the total can change
// between the two queries).
func (q *Queries) ListTripsForUser(ctx context.Context, arg ListTripsForUserParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsForUser,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.TimeZone,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BaseCurrency,
			&i.OpSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrip = `-- name: SoftDeleteTrip :execrows
UPDATE trips
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteTripParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) SoftDeleteTrip(ctx context.Context, arg SoftDeleteTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTrip, arg.DeletedAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tripExists = `-- name: TripExists :one
SELECT EXISTS (SELECT 1 FROM trips WHERE id = $1)
`

func (q *Queries) TripExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tripExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET name        = $1,
    description = $2,
    start_date  = $3,
    end_date    = $4,
    time_zone   = $5,
    version     = version + 1,
    updated_at  = $6
WHERE id = $7 AND version = $8 AND deleted_at IS NULL
RETURNING id, name, description, start_date, end_date, time_zone, version, created_at, updated_at, deleted_at, base_currency, op_seq
`

type UpdateTripParams struct {
	Name        string
	Description string
	StartDate   *time.Time
	EndDate     *time.Time
	TimeZone    string
	UpdatedAt   time.Time
	ID          uuid.UUID
	Version     int32
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.TimeZone,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimeZone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BaseCurrency,
		&i.OpSeq,
	)
	return i, err
}
