// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, display_name, email_verified_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, display_name, email_verified_at, version, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt *time.Time
}

// Queries for the users table.
//
// Conventions used throughout this directory:
//   - IDs are always supplied by the application (UUIDv7), never defaulted by the database.
//   - updated_at is set explicitly, never by a trigger, so Stage 2 can substitute an
//     operation's server timestamp.
//   - Every mutating query that participates in optimistic concurrency ends with
//     `AND version = @version` and RETURNS the row, so a zero-row result is detectable.
//   - Soft-deleted rows are excluded by every read unless the name says otherwise.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, email_verified_at, version, created_at, updated_at, deleted_at FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

// lower(email) matches the users_email_lower_uq functional index exactly. The caller passes
// an already-normalised address; normalising on both sides would still be correct but would
// hide which side owns the rule.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, email_verified_at, version, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = $1,
    version    = version + 1,
    updated_at = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	DeletedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email             = $1,
    display_name      = $2,
    password_hash     = $3,
    email_verified_at = $4,
    version           = version + 1,
    updated_at        = $5
WHERE id = $6 AND version = $7 AND deleted_at IS NULL
RETURNING id, email, password_hash, display_name, email_verified_at, version, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email           string
	DisplayName     string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	UpdatedAt       time.Time
	ID              uuid.UUID
	Version         int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1)
`

// Used only to distinguish "not found" from "version conflict" after a zero-row update.
// Deliberately ignores deleted_at: a soft-deleted row still explains why the update missed.
func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
