// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAllUserTokensForPurpose = `-- name: ConsumeAllUserTokensForPurpose :execrows
UPDATE user_tokens SET consumed_at = $1
WHERE user_id = $2 AND purpose = $3 AND consumed_at IS NULL
`

type ConsumeAllUserTokensForPurposeParams struct {
	ConsumedAt *time.Time
	UserID     uuid.UUID
	Purpose    string
}

// Issuing a new reset link must retire the previous one, or every link ever mailed stays
// live until it expires — turning an old inbox into a standing account takeover.
func (q *Queries) ConsumeAllUserTokensForPurpose(ctx context.Context, arg ConsumeAllUserTokensForPurposeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAllUserTokensForPurpose, arg.ConsumedAt, arg.UserID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeUserToken = `-- name: ConsumeUserToken :execrows
UPDATE user_tokens SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
`

type ConsumeUserTokenParams struct {
	ConsumedAt *time.Time
	ID         uuid.UUID
}

// `consumed_at IS NULL` makes single use atomic. Two requests racing on the same reset link
// produce exactly one winner; the loser gets zero rows and is rejected.
func (q *Queries) ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeUserToken, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserToken = `-- name: CreateUserToken :one

INSERT INTO user_tokens (id, user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, purpose, token_hash, expires_at, consumed_at, created_at
`

type CreateUserTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
}

// Queries for user_tokens: single-use email verification and password reset tokens.
func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRow(ctx, createUserToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredUserTokens = `-- name: DeleteExpiredUserTokens :execrows
DELETE FROM user_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredUserTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUserTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserTokenByHash = `-- name: GetUserTokenByHash :one
SELECT id, user_id, purpose, token_hash, expires_at, consumed_at, created_at FROM user_tokens WHERE token_hash = $1
`

// Unfiltered, like GetRefreshTokenByHash: the service needs to distinguish "unknown",
// "expired" and "already consumed" to return the right message and the right log line.
func (q *Queries) GetUserTokenByHash(ctx context.Context, tokenHash []byte) (UserToken, error) {
	row := q.db.QueryRow(ctx, getUserTokenByHash, tokenHash)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
