// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const castVote = `-- name: CastVote :one

INSERT INTO option_votes (id, slot_id, trip_id, user_id, option_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (slot_id, user_id) DO UPDATE
SET option_id  = EXCLUDED.option_id,
    version    = option_votes.version + 1,
    updated_at = now()
RETURNING id, slot_id, trip_id, user_id, option_id, version, created_at, updated_at
`

type CastVoteParams struct {
	ID       uuid.UUID
	SlotID   uuid.UUID
	TripID   uuid.UUID
	UserID   uuid.UUID
	OptionID *uuid.UUID
}

// Queries for option_votes.
//
// One row per (slot_id, user_id) with one mutable field: a last-writer-wins register. There
// is no delete — retraction sets option_id to NULL — which is what keeps the register shape
// and, in Stage 2, makes a vote the simplest convergent entity in the system.
// Upsert on (slot_id, user_id). This is why "change my vote" is a single round trip and a
// single row: without ON CONFLICT the caller would have to read first and then decide
// between INSERT and UPDATE, which is a race between two of the member's own devices.
//
// The version bump on conflict is what an optimistic reader observes; the vote itself is
// last-writer-wins by design, so this query deliberately does NOT take an expected version.
// Requiring one would make a member's second click fail rather than simply win, which is not
// what anyone means by changing their mind.
func (q *Queries) CastVote(ctx context.Context, arg CastVoteParams) (OptionVote, error) {
	row := q.db.QueryRow(ctx, castVote,
		arg.ID,
		arg.SlotID,
		arg.TripID,
		arg.UserID,
		arg.OptionID,
	)
	var i OptionVote
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.UserID,
		&i.OptionID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVotesForOption = `-- name: DeleteVotesForOption :execrows
DELETE FROM option_votes WHERE option_id = $1
`

// Used when an option is hard-deleted. Soft deletion does NOT call this: votes for a
// tombstoned option are retained so that undeleting restores the group's expressed
// preferences rather than silently discarding them.
func (q *Queries) DeleteVotesForOption(ctx context.Context, optionID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVotesForOption, optionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVote = `-- name: GetVote :one
SELECT id, slot_id, trip_id, user_id, option_id, version, created_at, updated_at FROM option_votes WHERE slot_id = $1 AND user_id = $2
`

type GetVoteParams struct {
	SlotID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetVote(ctx context.Context, arg GetVoteParams) (OptionVote, error) {
	row := q.db.QueryRow(ctx, getVote, arg.SlotID, arg.UserID)
	var i OptionVote
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.TripID,
		&i.UserID,
		&i.OptionID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVotesForSlot = `-- name: ListVotesForSlot :many
SELECT id, slot_id, trip_id, user_id, option_id, version, created_at, updated_at FROM option_votes WHERE slot_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListVotesForSlot(ctx context.Context, slotID uuid.UUID) ([]OptionVote, error) {
	rows, err := q.db.Query(ctx, listVotesForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionVote{}
	for rows.Next() {
		var i OptionVote
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.TripID,
			&i.UserID,
			&i.OptionID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesForTrip = `-- name: ListVotesForTrip :many
SELECT id, slot_id, trip_id, user_id, option_id, version, created_at, updated_at FROM option_votes WHERE trip_id = $1 ORDER BY slot_id, created_at, id
`

// Stage 2 resync: every vote in a sync room.
func (q *Queries) ListVotesForTrip(ctx context.Context, tripID uuid.UUID) ([]OptionVote, error) {
	rows, err := q.db.Query(ctx, listVotesForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionVote{}
	for rows.Next() {
		var i OptionVote
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.TripID,
			&i.UserID,
			&i.OptionID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tallyVotesForSlot = `-- name: TallyVotesForSlot :many
SELECT v.option_id, count(*) AS vote_count
FROM option_votes v
JOIN slot_options o ON o.id = v.option_id AND o.deleted_at IS NULL
WHERE v.slot_id = $1 AND v.option_id IS NOT NULL
GROUP BY v.option_id
ORDER BY vote_count DESC, v.option_id
`

type TallyVotesForSlotRow struct {
	OptionID  *uuid.UUID
	VoteCount int64
}

// Retractions (option_id IS NULL) are excluded: a withdrawn vote counts for nothing, but the
// row stays so the register keeps exactly one entry per member.
//
// Votes for SOFT-DELETED options are also excluded (D71), which is why this joins rather than
// grouping the vote table alone. Two things are true at once and both are wanted: a withdrawn
// candidate must not appear in a live tally, and the vote ROWS are retained so that undeleting
// the option restores the group's expressed preferences rather than silently discarding them.
//
// Filtered here in SQL rather than in Go so there is ONE definition of "a visible vote".
// The same rule applied in two places is the same rule until someone changes one of them.
func (q *Queries) TallyVotesForSlot(ctx context.Context, slotID uuid.UUID) ([]TallyVotesForSlotRow, error) {
	rows, err := q.db.Query(ctx, tallyVotesForSlot, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TallyVotesForSlotRow{}
	for rows.Next() {
		var i TallyVotesForSlotRow
		if err := rows.Scan(&i.OptionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
