package domain

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// ID is the identifier type for every entity in the system.
//
// It is a type alias rather than a defined type so that uuid's methods and the pgx type
// mappings work without conversion noise at every boundary. Per-entity ID types (TripID,
// UserID, ...) would buy compile-time protection against mixing them up, at the cost of a
// conversion at every call site; with this few entity types that trade is not worth it.
//
// github.com/google/uuid is the one third-party import allowed in this package. It is a
// leaf value-type library — no I/O, no framework, no transitive dependencies — so it sits
// in the same category as the standard library. It is explicitly allowlisted in
// arch_test.go so that this stays an intentional exception rather than becoming the first
// step of unnoticed drift.
type ID = uuid.UUID

// NilID is the zero identifier. It is never a valid persisted ID.
var NilID = uuid.Nil

// NewID returns a new UUIDv7.
//
// v7 rather than v4 for two reasons that both matter here:
//
//  1. IDs are generated by the application and by clients, never by the database
//     (no DEFAULT gen_random_uuid()). Optimistic UI and offline editing both require
//     naming an entity before the server has seen it; a database-assigned ID would force
//     an ID-reconciliation pass on every acknowledgement.
//  2. v7 is time-ordered, so primary-key inserts land at the right edge of the B-tree
//     instead of scattering across it the way random v4 keys do.
//
// It panics if the system entropy source fails, matching uuid.New()'s own behaviour: a
// process that cannot generate identifiers cannot do anything useful, and returning an
// error here would push an unhandleable condition into every call site.
func NewID() ID {
	id, err := uuid.NewV7()
	if err != nil {
		panic(fmt.Sprintf("domain: cannot generate UUIDv7: %v", err))
	}
	return id
}

// ParseID parses a textual identifier, returning a validation error on failure so that
// handlers can surface it as a field-level problem rather than a generic 400.
func ParseID(field, s string) (ID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		ve := &ValidationError{}
		ve.Add(field, "invalid_uuid", "must be a valid UUID")
		return NilID, ve
	}
	return id, nil
}

// Clock abstracts the passage of time.
//
// Token expiry, session lifetime, and rotation windows are all time-dependent, and tests
// for them must not sleep. Every service takes a Clock; production wires SystemClock.
type Clock interface {
	Now() time.Time
}

// SystemClock is the production Clock.
type SystemClock struct{}

// Now returns the current time, normalised to UTC.
//
// Normalising here rather than at each call site means a local-time value can never leak
// into a timestamptz column or a token expiry comparison.
func (SystemClock) Now() time.Time { return time.Now().UTC() }
